from pathlib import Path
p=Path('automatic_captions.py');s=p.read_text(encoding='utf-8');s=s.replace('from pathlib import Path','from pathlib import Path\nimport unicodedata');s=s.replace("    bridge=(ROOT/'caption_bridge.lua').read_text(encoding='utf-8')",'''    bridge=(ROOT/'caption_bridge.lua').read_text(encoding='utf-8-sig')
    ranges=[]
    for cp in range(0x110000):
        if unicodedata.category(chr(cp)).startswith('P'):
            if ranges and cp==ranges[-1][1]+1:ranges[-1][1]=cp
            else:ranges.append([cp,cp])
    bridge=bridge.replace('PUNCTUATION_RANGES',','.join('{'+str(a)+','+str(b)+'}' for a,b in ranges))''');p.write_text(s,encoding='utf-8')
p=Path('caption_bridge.lua');s=p.read_text(encoding='utf-8');s=s.replace('local function clean(text)','''local punctuationRanges={PUNCTUATION_RANGES}
local function punctuation(cp,ch)
 if ch:match('%p') then return true end
 for _,r in ipairs(punctuationRanges) do if cp>=r[1] and cp<=r[2] then return true end end
 return false
end
local function clean(text)''');a=s.index("  elseif not ch:match('%p')");b=s.index(' then table.insert(chars,ch) end',a);s=s[:a]+"  elseif not punctuation(cp,ch)"+s[b:];p.write_text(s,encoding='utf-8')
p=Path('automatic_cut.py');s=p.read_text(encoding='utf-8').replace('def send(result,progress=lambda s:None,add_sfx=False):','def send(result,progress=lambda s:None,add_sfx=False,add_captions=True):');s=s.replace("    audio=audio_sidecars(result['source'],progress)","    caption_script=''\n    if add_captions:\n        from automatic_captions import lua_for_captions\n        caption_script=lua_for_captions(result['microphone'])\n    audio=audio_sidecars(result['source'],progress)");s=s.replace('result=dict(result,sfx_enabled=add_sfx,','result=dict(result,captions_enabled=add_captions,sfx_enabled=add_sfx,');s=s.replace("progress('Opening your automatic cut in Resolve…')","progress('Creating your cut, subtitles and Snap Captions in Resolve…' if add_captions else 'Opening your automatic cut in Resolve…')");s=s.replace("        f.write(sfx_script)","        f.write(sfx_script)\n        if caption_script:\n            f.write('\\nlocal captionOK,captionError=pcall(function()\\n'+caption_script+'\\nend)\\nif not captionOK then print(\\\"AUTO_CAPTIONS_FAILED \\\"..tostring(captionError)) end\\n')");s=s.replace("text=True,timeout=60,creationflags=", "text=True,timeout=3600 if add_captions else 60,creationflags=");s=s.replace("    save_json(ROOT/'analysis'/'last-automatic-cut.json',result)","    if add_captions:\n        import re\n        match=re.search(r'AUTO_CAPTIONS_VERIFIED (\\d+)',output)\n        result['caption_count']=int(match.group(1)) if match else 0\n        result['captions_verified']=bool(match)\n        if not match:result['caption_error']=output.split('AUTO_CAPTIONS_FAILED ',1)[-1].splitlines()[0] if 'AUTO_CAPTIONS_FAILED ' in output else 'Resolve did not confirm captions.'\n    save_json(folder/'automatic-plan.json',result)\n    save_json(ROOT/'analysis'/'last-automatic-cut.json',result)");p.write_text(s,encoding='utf-8')
p=Path('automatic_review.py');s=p.read_text(encoding='utf-8');s=s.replace('def __init__(self,source,mic,sfx=True):super().__init__();self.source=source;self.mic=mic;self.sfx=sfx','def __init__(self,source,mic,sfx=True,captions=True):super().__init__();self.source=source;self.mic=mic;self.sfx=sfx;self.captions=captions');s=s.replace('add_sfx=self.sfx)', 'add_sfx=self.sfx,add_captions=self.captions)');s=s.replace('        self.create=QPushButton',"        self.captions=QCheckBox('Automatic Snap Captions · 15 characters per line · no punctuation');self.captions.setChecked(True);layout.addWidget(self.captions)\n        self.create=QPushButton",1);s=s.replace('self.sfx.setEnabled(False);','self.sfx.setEnabled(False);self.captions.setEnabled(False);').replace('self.sfx.setEnabled(True);','self.sfx.setEnabled(True);self.captions.setEnabled(True);');s=s.replace('self.voice.currentIndex(),self.sfx.isChecked())','self.voice.currentIndex(),self.sfx.isChecked(),self.captions.isChecked())');s=s.replace('    def failed(self,message):',"        if result.get('captions_enabled'):\n            if result.get('captions_verified'):\n                self.status.setText(self.status.text()+f'\\n{result[\"caption_count\"]} Snap Captions · 15 characters per line · no punctuation.')\n            else:self.status.setText(self.status.text()+'\\nThe cut is ready, but captions failed: '+result.get('caption_error','See export details.'))\n    def failed(self,message):");s=s.replace('self.resize(780,730)','self.resize(840,800)');p.write_text(s,encoding='utf-8')
